### ISSUE TITLE
canvas绘图模糊问题

### ISSUE THREAD

**Issue by paper520** [yelloxing/image2D#11]
**内容**
由于canvas2D绘图的特殊方式，会导致对外扩张0.5个单位，这可能导致线条模糊，需要改进。

**原因**
有时候线条太模糊了，不美观。

**场景**
绘图

**补充**

```html
<canvas width="400" height="400" id="canvas" style="width:200px;height:200px"></canvas>
<script>

        var canvas = document.getElementById('canvas');
        var ctx = canvas.getContext('2d');
        ctx.scale(2, 2);
        ctx.strokeStyle = '#000';
        ctx.lineWidth = 1;
        ctx.strokeRect(10, 10, 100, 100);

</script>
```

**Comment by yelloxing** [comment]
已经初步修复，待验证一段时间会在下一个版本（v1.1.1以后版本）更新

**Comment by yelloxing** [comment]
如果还有问题，请提供一下设备像素比：
![屏幕快照 2019-07-11 09 52 28](https://user-images.githubusercontent.com/23074691/61016300-bf98f980-a3c1-11e9-826b-ea4661692434.png)

**Comment by yelloxing** [comment]
此问题在思否上也有提问，对应提问是[关于canvas2D绘图出现锯齿现象的解决方案探讨或心得交流](https://segmentfault.com/q/1010000021030051)
