### ISSUE TITLE
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .

### ISSUE THREAD

**Issue by yelloxing** [yelloxing/image2D#15]
I am using  karma and i am trying to use travis ci to run my tests but i get this error:

0.00s$ export CHROME_BIN=chromium-browser
before_install.2
0.00s$ export DISPLAY=:99.0
0.00s$ sh -e /etc/init.d/xvfb start
sh: 0: Can't open /etc/init.d/xvfb
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .

This is my travis.yml file:

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
language: node_js
node_js:
  - node
script:
  - npm install
  - npm run unit

**Comment by dhilt** [comment]
Use following

```
language: node_js
node_js:
 - "stable"
before_install:
 - export CHROME_BIN=chromium-browser
services:
 - xvfb
script:
 - npm install
 - npm run unit
```

The details with further reading could be found [here](https://stackoverflow.com/a/57517901/3211932).

**Comment by yelloxing** [comment]
This still doesn't work. 
Code location: 
https://github.com/yelloxing/image2D/blob/travis.yml-test/.travis.yml

![屏幕快照 2019-08-16 11 59 05](https://user-images.githubusercontent.com/23074691/63142668-45414200-c01d-11e9-9da7-b87819096447.png)

**Comment by yelloxing** [comment]
It seems to have something to do with karma itself. I'll try again later.

**Comment by chen351012** [comment]
Why not suddenly?

**Comment by paper520** [comment]
Did the sudden upgrade of travis-ci.org cause it? Why is it incompatible with the old way of writing?

**Comment by yelloxing** [comment]
Can you help solve this problem? @dhilt

**Comment by tear520** [comment]
Travis.yml has been deleted.

**Comment by yelloxing** [comment]
what? @tear520

**Comment by yelloxing** [comment]
废弃

**Comment by wbotelhos** [comment]
Thank you @dhilt , it worked and gave me a much clean config. <3
