### ISSUE TITLE
【Stop 停用】Please submit the new features you wish to provide in the future

### ISSUE THREAD

**Issue by yelloxing** [yelloxing/image2D#18]
Reminder(温馨提示)
----------------

Please submit the new features you wish to provide in the future. We will draw conclusions based on the results of the discussion and implement the accepted proposals as soon as possible.

请在这里提交未来希望提供的新特性，我们会根据讨论的结果给出结论，并尽快实现被接受的提案！

**Comment by yelloxing** [comment]
### 关于treeLayout布局
**为了方便绘制动画效果和更灵活的控制(比如[circle tree](https://yelloxing.github.io/Image-Demo/index.html#/tree-radial)慢慢展开效果，从内到外)，计划在未来版本中每个结点中多添加一项deep用来表示树的层次，从0开始编号。**

**Comment by yelloxing** [comment]
### 旭日布局
**绘制这个简单的[monochrome](https://github.com/yelloxing/Image-Demo/blob/master/src/demos/Sunburst/monochrome.vue)旭日图后感觉，还是有必要在未来考虑添加这个布局计算的，虽然它和饼布局很像，可是还是有很大的差异，提供对提高开发效率和优化代码可读性是有价值的。**

**Comment by yelloxing** [comment]
### 关于动画

**一方面：考虑是否在可能的时候使用浏览器原生动画方法**

**另一方面：动画控制接口是否可以更加灵活，比如快进，回退，暂停等操作**

**Comment by yelloxing** [comment]
### 地图映射

**针对各种地图经纬度到坐标的映射方法，是否有必要提供，还是说提供一种应用范围最广的？**

**Comment by yelloxing** [comment]
### 获得颜色值

**返回一个颜色感觉的一系列颜色值，在寻求一个稳定，好看的计算方法。**

**Comment by paper520** [comment]
**力布局**

一些复杂的关系，是否可以提供一个力布局。

**Comment by yelloxing** [comment]
添加新的地图投影：墨卡托(Mercator)投影，又称等角正切圆柱投影

**Comment by yelloxing** [comment]
添加新的布局：force力布局

![屏幕快照 2020-09-09 14 29 48](https://user-images.githubusercontent.com/23074691/92562733-0675ce00-f2a9-11ea-8eee-02cc3b9a1a81.png)

**Comment by yelloxing** [comment]
由于canvas和svg不同，无法很方便的为某个图形绑定交互事件，是否有好的解决方案。

**Comment by yelloxing** [comment]
添加新的布局：条形图布局

关于类似下面的图形，是否有类似tree或pie等的布局来方便我们绘制，虽然手动计算并不难。

![屏幕快照 2020-09-09 14 40 20](https://user-images.githubusercontent.com/23074691/92563705-8fd9d000-f2aa-11ea-8275-53b3eacaee91.png)

**Comment by yelloxing** [comment]
常见的坐标无法两种：直角坐标系和极坐标系，在绘制的时候，是否有好的方式提供一个简单的对象，通过配置以后，辅助计算实际绘制的（x,y），和地图类似。

**Comment by yelloxing** [comment]
饼图布局

和树图布局类似，是否需要在考虑数据改变的时候，优化动画，或者说，以后的布局都统一内置处理好动画。

我们需要进行一下讨论

**Comment by yelloxing** [comment]
这个issue停止使用，如果有疑惑或者相关RFC,请直接新建issue告诉我们即可！
