### ISSUE TITLE
模板字符串标签类型判断

### ISSUE THREAD

**Issue by paper520** [yelloxing/image2D#2]
火狐浏览器html结点判断有误（svg还是html标签）

**Comment by yelloxing** [comment]
![屏幕快照 2019-05-15 10 13 24](https://user-images.githubusercontent.com/23074691/57744302-3fc11c80-76fb-11e9-8a4e-adac60d76289.png)

**Comment by yelloxing** [comment]
除了火狐，其余目前测试都通过了

**Comment by yelloxing** [comment]
目前已经放弃自动判断机制

**Comment by yelloxing** [comment]
准备再次寻找
