### ISSUE TITLE
[Vue warn]: Unknown custom element: <ui-radio> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by yelloxing** [yelloxing/image2D#23]
我想优化一下文档，开发一些有趣的交互小组件，可是：

```js
window.vm = new Vue({

    // 挂载组件
    components: {
        UiRadio
    }

});
```

如上，我全局注册了自定义的.vue组件，使用的时候：

```html
<ui-radio />
```

报下列错误：

[Vue warn]: Unknown custom element: <ui-radio> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in XXX.vue

**Comment by paper520** [comment]
你这样是因为使用前没有注册，你需要这样：

```js
Vue.component('uiRadio',UiRadio);
```
