### ISSUE TITLE
新增颜色生成方法

### ISSUE THREAD

**Issue by yelloxing** [yelloxing/image2D#29]
**内容（content）**
新增一个可以根据一定的规则生成比较稳定的一定数目的颜色的方法

**原因（Reason）**
有时候绘图的可能需要用颜色区分不同的对象，如果对象个数未知，手动设置颜色比较麻烦而且有溢出的风险。

**Comment by yelloxing** [comment]
给定任意一个合法的css颜色字符串，把颜色统一转变成rgba格式，返回一个数组[r,g,b,a]：

```
var rgbaArray=$$.formatColor(colorString);
```

传递需要的颜色个数，返回一组随机色彩：
```
var colors=$$.getRandomColors(number);
```

**Comment by hazybby** [comment]
感觉组件是独立的东西，可以脱离这个项目，除非是有必要的理由，不然不利于此项目的长期维护。
