### ISSUE TITLE
读取配置文件失败：文件【E:\github\image2D\cuf.conf.js】不存在！

### ISSUE THREAD

**Issue by paper520** [yelloxing/image2D#3]
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by paper520** [comment]
```bash
npm run build
```
windows7下使用cmd 打包报上面错误！

**Comment by yelloxing** [comment]
这个应该是cuf拼接路径问题，修改使用默认路径后可以了。
