### ISSUE TITLE
npm ERR! Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by paper520** [yelloxing/image2D#4]
```bash
npm start
```

windows7上执行上面命令报错

**Comment by paper520** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle image2d@0.0.1-dev~prestart: image2d@0.0.1-dev
6 info lifecycle image2d@0.0.1-dev~start: image2d@0.0.1-dev
7 verbose lifecycle image2d@0.0.1-dev~start: unsafe-perm in lifecycle true
8 verbose lifecycle image2d@0.0.1-dev~start: PATH: D:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;E:\github\image2D\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\nodejs\;D:\Program Files (x86)\Microsoft VS Code\bin;;D:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm;.;;.;;.;
9 verbose lifecycle image2d@0.0.1-dev~start: CWD: E:\github\image2D
10 silly lifecycle image2d@0.0.1-dev~start: Args: [ '/d /s /c',
10 silly lifecycle   'npm install && cuf explain --config cuf.conf.js' ]
11 silly lifecycle image2d@0.0.1-dev~start: Returned: code: 4294963248  signal: null
12 info lifecycle image2d@0.0.1-dev~start: Failed to exec start script
13 verbose stack Error: image2d@0.0.1-dev start: `npm install && cuf explain --config cuf.conf.js`
13 verbose stack Exit status 4294963248
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid image2d@0.0.1-dev
15 verbose cwd E:\github\image2D
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 4294963248
22 error image2d@0.0.1-dev start: `npm install && cuf explain --config cuf.conf.js`
22 error Exit status 4294963248
23 error Failed at the image2d@0.0.1-dev start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294963248, true ]

**Comment by yelloxing** [comment]
你这个可能是命令中断导致的
